### ISSUE TITLE
Item page should be identified by user's username instead of email

### ISSUE THREAD

**Issue by benjaminheng** [cs2102-database-systems-g11/stuffy#13]
https://github.com/cs2102-database-systems-g11/stuffy/commit/23ed54ebf43e40f1c4fefbb321e4319e5c27f97e#diff-8de1bb9a3431a51d784147deff0df07bL9

Email should be hidden to other users.

Bidders should be identified by their usernames instead too.

**Comment by tanweijun** [comment]
a10a831b5e109ddfc06f0a9813bdcbc0669cdfa2
