### ISSUE TITLE
User can see a list of advertisements

### ISSUE THREAD

**Issue by benjaminheng** [cs2102-database-systems-g11/stuffy#5]
/browse.php

**Comment by tanweijun** [comment]
browse.php displays all items now but clicking the item doesn't do anything 022ee66734077a9ce4702f6d593a74e5af83e3ee

**Comment by benjaminheng** [comment]
Item now links to `/item.php?user=:username&name=:item_name`. File item.php implementation is part of #8. Closing if there's nothing else for this issue.
